export const LOADING_SET_STATUS = 'LOADING_SET_STATUS';
export const CONTACTS_LOAD_DATA = 'CONTACTS_LOAD_DATA';
export const CONTACTS_SET_FILTERED = 'CONTACTS_SET_FILTERED';
export const NOTIFICATION_SET_MESSAGE = 'NOTIFICATION_SET_MESSAGE';
